package main

var capitals = []string{
	"Kabul",
	"Tirana",
	"Algiers",
	"Andorra la Vella",
	"Luanda",
	"Saint John's",
	"Buenos Aires",
	"Yerevan",
	"Canberra",
	"Vienna",
	"Baku",
	"Nassau",
	"Manama",
	"Dhaka",
	"Bridgetown",
	"Minsk",
	"Brussels",
	"Belmopan",
	"Porto-Novo",
	"Thimphu",
	"Sucre",
	"Sarajevo",
	"Gaborone",
	"Brasília",
	"Bandar Seri Begawan",
	"Sofia",
	"Ouagadougou",
	"Gitega",
	"Phnom Penh",
	"Yaoundé",
	"Ottawa",
	"Praia",
	"Bangui",
	"N'Djamena",
	"Santiago",
	"Beijing",
	"Bogotá",
	"Moroni",
	"Brazzaville",
	"Kinshasa",
	"San José",
	"Zagreb",
	"Havana",
	"Nicosia",
	"Prague",
	"Copenhagen",
	"Djibouti",
	"Roseau",
	"Santo Domingo",
	"Quito",
	"Cairo",
	"San Salvador",
	"Malabo",
	"Asmara",
	"Tallinn",
	"Mbabane",
	"Addis Ababa",
	"Suva",
	"Helsinki",
	"Paris",
	"Libreville",
	"Banjul",
	"Tbilisi",
	"Berlin",
	"Accra",
	"Athens",
	"St. George's",
	"Guatemala City",
	"Conakry",
	"Bissau",
	"Georgetown",
	"Port-au-Prince",
	"Tegucigalpa",
	"Budapest",
	"Reykjavik",
	"New Delhi",
	"Jakarta",
	"Tehran",
	"Baghdad",
	"Dublin",
	"Jerusalem",
	"Rome",
	"Kingston",
	"Tokyo",
	"Amman",
	"Astana",
	"Nairobi",
	"Tarawa",
	"Pyongyang",
	"Seoul",
	"Kuwait City",
	"Bishkek",
	"Vientiane",
	"Riga",
	"Beirut",
	"Maseru",
	"Monrovia",
	"Tripoli",
	"Vaduz",
	"Vilnius",
	"Luxembourg City",
	"Antananarivo",
	"Lilongwe",
	"Kuala Lumpur",
	"Malé",
	"Bamako",
	"Valletta",
	"Majuro",
	"Nouakchott",
	"Port Louis",
	"Mexico City",
	"Palikir",
	"Chișinău",
	"Monaco",
	"Ulaanbaatar",
	"Podgorica",
	"Rabat",
	"Maputo",
	"Naypyidaw",
	"Windhoek",
	"Yaren District",
	"Kathmandu",
	"Amsterdam",
	"Wellington",
	"Managua",
	"Niamey",
	"Abuja",
	"Oslo",
	"Muscat",
	"Islamabad",
	"Ngerulmud",
	"Panama City",
	"Port Moresby",
	"Asunción",
	"Lima",
	"Manila",
	"Warsaw",
	"Lisbon",
	"Doha",
	"Bucharest",
	"Moscow",
	"Kigali",
	"Basseterre",
	"Castries",
	"Kingstown",
	"Apia",
	"San Marino",
	"São Tomé",
	"Riyadh",
	"Dakar",
	"Belgrade",
	"Victoria",
	"Freetown",
	"Singapore",
	"Bratislava",
	"Ljubljana",
	"Honiara",
	"Mogadishu",
	"Pretoria",
	"Juba",
	"Madrid",
	"Sri Jayawardenepura Kotte",
	"Khartoum",
	"Paramaribo",
	"Stockholm",
	"Bern",
	"Damascus",
	"Taipei",
	"Dushanbe",
	"Dodoma",
	"Bangkok",
	"Dili",
	"Lomé",
	"Nukuʻalofa",
	"Port of Spain",
	"Tunis",
	"Ankara",
	"Ashgabat",
	"Funafuti",
	"Kampala",
	"Kyiv",
	"Abu Dhabi",
	"London",
	"Washington, D.C.",
	"Montevideo",
	"Tashkent",
	"Port Vila",
	"Vatican City",
	"Caracas",
	"Hanoi",
	"Sana'a",
	"Lusaka",
	"Harare",
}

var capitalCountryMap = map[string]string{
	"Harare":                    "Zimbabwe",
	"Lusaka":                    "Zambia",
	"Sana'a":                    "Yemen",
	"Hanoi":                     "Vietnam",
	"Caracas":                   "Venezuela",
	"Vatican City":              "Vatican City",
	"Port Vila":                 "Vanuatu",
	"Tashkent":                  "Uzbekistan",
	"Montevideo":                "Uruguay",
	"Washington, D.C.":          "United States",
	"London":                    "United Kingdom",
	"Abu Dhabi":                 "United Arab Emirates",
	"Kyiv":                      "Ukraine",
	"Kampala":                   "Uganda",
	"Funafuti":                  "Tuvalu",
	"Ashgabat":                  "Turkmenistan",
	"Ankara":                    "Turkey",
	"Tunis":                     "Tunisia",
	"Port of Spain":             "Trinidad and Tobago",
	"Nukuʻalofa":                "Tonga",
	"Lomé":                      "Togo",
	"Dili":                      "Timor-Leste",
	"Bangkok":                   "Thailand",
	"Dodoma":                    "Tanzania",
	"Dushanbe":                  "Tajikistan",
	"Taipei":                    "Taiwan",
	"Damascus":                  "Syria",
	"Bern":                      "Switzerland",
	"Stockholm":                 "Sweden",
	"Paramaribo":                "Suriname",
	"Khartoum":                  "Sudan",
	"Sri Jayawardenepura Kotte": "Sri Lanka",
	"Madrid":                    "Spain",
	"Juba":                      "South Sudan",
	"Pretoria":                  "South Africa",
	"Mogadishu":                 "Somalia",
	"Honiara":                   "Solomon Islands",
	"Ljubljana":                 "Slovenia",
	"Bratislava":                "Slovakia",
	"Singapore":                 "Singapore",
	"Freetown":                  "Sierra Leone",
	"Victoria":                  "Seychelles",
	"Belgrade":                  "Serbia",
	"Dakar":                     "Senegal",
	"Riyadh":                    "Saudi Arabia",
	"São Tomé":                  "Sao Tome and Principe",
	"San Marino":                "San Marino",
	"Apia":                      "Samoa",
	"Kingstown":                 "Saint Vincent and the Grenadines",
	"Castries":                  "Saint Lucia",
	"Basseterre":                "Saint Kitts and Nevis",
	"Kigali":                    "Rwanda",
	"Moscow":                    "Russia",
	"Bucharest":                 "Romania",
	"Doha":                      "Qatar",
	"Lisbon":                    "Portugal",
	"Warsaw":                    "Poland",
	"Manila":                    "Philippines",
	"Lima":                      "Peru",
	"Asunción":                  "Paraguay",
	"Port Moresby":              "Papua New Guinea",
	"Panama City":               "Panama",
	"Ngerulmud":                 "Palau",
	"Islamabad":                 "Pakistan",
	"Muscat":                    "Oman",
	"Oslo":                      "Norway",
	"Abuja":                     "Nigeria",
	"Niamey":                    "Niger",
	"Managua":                   "Nicaragua",
	"Wellington":                "New Zealand",
	"Amsterdam":                 "Netherlands",
	"Kathmandu":                 "Nepal",
	"Yaren District":            "Nauru",
	"Windhoek":                  "Namibia",
	"Naypyidaw":                 "Myanmar",
	"Maputo":                    "Mozambique",
	"Rabat":                     "Morocco",
	"Podgorica":                 "Montenegro",
	"Ulaanbaatar":               "Mongolia",
	"Monaco":                    "Monaco",
	"Chișinău":                  "Moldova",
	"Palikir":                   "Micronesia",
	"Mexico City":               "Mexico",
	"Port Louis":                "Mauritius",
	"Nouakchott":                "Mauritania",
	"Majuro":                    "Marshall Islands",
	"Valletta":                  "Malta",
	"Bamako":                    "Mali",
	"Malé":                      "Maldives",
	"Kuala Lumpur":              "Malaysia",
	"Lilongwe":                  "Malawi",
	"Antananarivo":              "Madagascar",
	"Luxembourg City":           "Luxembourg",
	"Vilnius":                   "Lithuania",
	"Vaduz":                     "Liechtenstein",
	"Tripoli":                   "Libya",
	"Monrovia":                  "Liberia",
	"Maseru":                    "Lesotho",
	"Beirut":                    "Lebanon",
	"Riga":                      "Latvia",
	"Vientiane":                 "Laos",
	"Bishkek":                   "Kyrgyzstan",
	"Kuwait City":               "Kuwait",
	"Seoul":                     "South Korea",
	"Pyongyang":                 "North Korea",
	"Tarawa":                    "Kiribati",
	"Nairobi":                   "Kenya",
	"Astana":                    "Kazakhstan",
	"Amman":                     "Jordan",
	"Tokyo":                     "Japan",
	"Kingston":                  "Jamaica",
	"Rome":                      "Italy",
	"Jerusalem":                 "Israel",
	"Dublin":                    "Ireland",
	"Baghdad":                   "Iraq",
	"Tehran":                    "Iran",
	"Jakarta":                   "Indonesia",
	"New Delhi":                 "India",
	"Reykjavik":                 "Iceland",
	"Budapest":                  "Hungary",
	"Tegucigalpa":               "Honduras",
	"Port-au-Prince":            "Haiti",
	"Georgetown":                "Guyana",
	"Bissau":                    "Guinea-Bissau",
	"Conakry":                   "Guinea",
	"Guatemala City":            "Guatemala",
	"St. George's":              "Grenada",
	"Athens":                    "Greece",
	"Accra":                     "Ghana",
	"Berlin":                    "Germany",
	"Tbilisi":                   "Georgia",
	"Banjul":                    "Gambia",
	"Libreville":                "Gabon",
	"Paris":                     "France",
	"Helsinki":                  "Finland",
	"Suva":                      "Fiji",
	"Addis Ababa":               "Ethiopia",
	"Mbabane":                   "Eswatini",
	"Tallinn":                   "Estonia",
	"Asmara":                    "Eritrea",
	"Malabo":                    "Equatorial Guinea",
	"San Salvador":              "El Salvador",
	"Cairo":                     "Egypt",
	"Quito":                     "Ecuador",
	"Santo Domingo":             "Dominican Republic",
	"Roseau":                    "Dominica",
	"Djibouti":                  "Djibouti",
	"Copenhagen":                "Denmark",
	"Prague":                    "Czech Republic",
	"Nicosia":                   "Cyprus",
	"Havana":                    "Cuba",
	"Zagreb":                    "Croatia",
	"San José":                  "Costa Rica",
	"Kinshasa":                  "Democratic Republic of the Congo",
	"Brazzaville":               "Republic of the Congo",
	"Moroni":                    "Comoros",
	"Bogotá":                    "Colombia",
	"Beijing":                   "China",
	"Santiago":                  "Chile",
	"N'Djamena":                 "Chad",
	"Bangui":                    "Central African Republic",
	"Praia":                     "Cape Verde",
	"Ottawa":                    "Canada",
	"Yaoundé":                   "Cameroon",
	"Phnom Penh":                "Cambodia",
	"Gitega":                    "Burundi",
	"Ouagadougou":               "Burkina Faso",
	"Sofia":                     "Bulgaria",
	"Bandar Seri Begawan":       "Brunei",
	"Brasília":                  "Brazil",
	"Gaborone":                  "Botswana",
	"Sarajevo":                  "Bosnia and Herzegovina",
	"Sucre":                     "Bolivia",
	"Thimphu":                   "Bhutan",
	"Porto-Novo":                "Benin",
	"Belmopan":                  "Belize",
	"Brussels":                  "Belgium",
	"Minsk":                     "Belarus",
	"Bridgetown":                "Barbados",
	"Dhaka":                     "Bangladesh",
	"Manama":                    "Bahrain",
	"Nassau":                    "Bahamas",
	"Baku":                      "Azerbaijan",
	"Vienna":                    "Austria",
	"Canberra":                  "Australia",
	"Yerevan":                   "Armenia",
	"Buenos Aires":              "Argentina",
	"Saint John's":              "Antigua and Barbuda",
	"Luanda":                    "Angola",
	"Andorra la Vella":          "Andorra",
	"Algiers":                   "Algeria",
	"Tirana":                    "Albania",
	"Kabul":                     "Afghanistan",
}

var nationalityMap = map[string]string{
	"Afghan":               "Afghanistan",
	"Albanian":             "Albania",
	"Algerian":             "Algeria",
	"Andorran":             "Andorra",
	"Angolan":              "Angola",
	"Antiguan":             "Antigua and Barbuda",
	"Argentine":            "Argentina",
	"Armenian":             "Armenia",
	"Australian":           "Australia",
	"Austrian":             "Austria",
	"Azerbaijani":          "Azerbaijan",
	"Bahamian":             "Bahamas",
	"Bahraini":             "Bahrain",
	"Bangladeshi":          "Bangladesh",
	"Barbadian":            "Barbados",
	"Belarusian":           "Belarus",
	"Belgian":              "Belgium",
	"Belizean":             "Belize",
	"Beninese":             "Benin",
	"Bhutanese":            "Bhutan",
	"Bolivian":             "Bolivia",
	"Bosnian":              "Bosnia and Herzegovina",
	"Botswanan":            "Botswana",
	"Brazilian":            "Brazil",
	"Bruneian":             "Brunei",
	"Bulgarian":            "Bulgaria",
	"Burkinabé":            "Burkina Faso",
	"Burundian":            "Burundi",
	"Cambodian":            "Cambodia",
	"Cameroonian":          "Cameroon",
	"Canadian":             "Canada",
	"Cape Verdean":         "Cape Verde",
	"Central African":      "Central African Republic",
	"Chadian":              "Chad",
	"Chilean":              "Chile",
	"Chinese":              "China",
	"Colombian":            "Colombia",
	"Comorian":             "Comoros",
	"Congolese":            "Republic of the Congo",
	"Congolese (DRC)":      "Democratic Republic of the Congo",
	"Costa Rican":          "Costa Rica",
	"Croatian":             "Croatia",
	"Cuban":                "Cuba",
	"Cypriot":              "Cyprus",
	"Czech":                "Czech Republic",
	"Danish":               "Denmark",
	"Djiboutian":           "Djibouti",
	"Dominican":            "Dominica",
	"Dominican (Republic)": "Dominican Republic",
	"Ecuadorian":           "Ecuador",
	"Egyptian":             "Egypt",
	"Salvadoran":           "El Salvador",
	"Equatorial Guinean":   "Equatorial Guinea",
	"Eritrean":             "Eritrea",
	"Estonian":             "Estonia",
	"Swazi":                "Eswatini",
	"Ethiopian":            "Ethiopia",
	"Fijian":               "Fiji",
	"Finnish":              "Finland",
	"French":               "France",
	"Gabonese":             "Gabon",
	"Gambian":              "Gambia",
	"Georgian":             "Georgia",
	"German":               "Germany",
	"Ghanaian":             "Ghana",
	"Greek":                "Greece",
	"Grenadian":            "Grenada",
	"Guatemalan":           "Guatemala",
	"Guinean":              "Guinea",
	"Bissau-Guinean":       "Guinea-Bissau",
	"Guyanese":             "Guyana",
	"Haitian":              "Haiti",
	"Honduran":             "Honduras",
	"Hungarian":            "Hungary",
	"Icelandic":            "Iceland",
	"Indian":               "India",
	"Indonesian":           "Indonesia",
	"Iranian":              "Iran",
	"Iraqi":                "Iraq",
	"Irish":                "Ireland",
	"Israeli":              "Israel",
	"Italian":              "Italy",
	"Jamaican":             "Jamaica",
	"Japanese":             "Japan",
	"Jordanian":            "Jordan",
	"Kazakh":               "Kazakhstan",
	"Kenyan":               "Kenya",
	"I-Kiribati":           "Kiribati",
	"North Korean":         "North Korea",
	"South Korean":         "South Korea",
	"Kuwaiti":              "Kuwait",
	"Kyrgyz":               "Kyrgyzstan",
	"Lao":                  "Laos",
	"Latvian":              "Latvia",
	"Lebanese":             "Lebanon",
	"Basotho":              "Lesotho",
	"Liberian":             "Liberia",
	"Libyan":               "Libya",
	"Liechtensteiner":      "Liechtenstein",
	"Lithuanian":           "Lithuania",
	"Luxembourgish":        "Luxembourg",
	"Malagasy":             "Madagascar",
	"Malawian":             "Malawi",
	"Malaysian":            "Malaysia",
	"Maldivian":            "Maldives",
	"Malian":               "Mali",
	"Maltese":              "Malta",
	"Marshallese":          "Marshall Islands",
	"Mauritanian":          "Mauritania",
	"Mauritian":            "Mauritius",
	"Mexican":              "Mexico",
	"Micronesian":          "Micronesia",
	"Moldovan":             "Moldova",
	"Monégasque":           "Monaco",
	"Mongolian":            "Mongolia",
	"Montenegrin":          "Montenegro",
	"Moroccan":             "Morocco",
	"Mozambican":           "Mozambique",
	"Burmese":              "Myanmar",
	"Namibian":             "Namibia",
	"Nauruan":              "Nauru",
	"Nepalese":             "Nepal",
	"Dutch":                "Netherlands",
	"New Zealander":        "New Zealand",
	"Nicaraguan":           "Nicaragua",
	"Nigerien":             "Niger",
	"Nigerian":             "Nigeria",
	"Norwegian":            "Norway",
	"Omani":                "Oman",
	"Pakistani":            "Pakistan",
	"Palauan":              "Palau",
	"Panamanian":           "Panama",
	"Papua New Guinean":    "Papua New Guinea",
	"Paraguayan":           "Paraguay",
	"Peruvian":             "Peru",
	"Filipino":             "Philippines",
	"Polish":               "Poland",
	"Portuguese":           "Portugal",
	"Qatari":               "Qatar",
	"Romanian":             "Romania",
	"Russian":              "Russia",
	"Rwandan":              "Rwanda",
	"Kittitian":            "Saint Kitts and Nevis",
	"Saint Lucian":         "Saint Lucia",
	"Vincentian":           "Saint Vincent and the Grenadines",
	"Samoan":               "Samoa",
	"San Marinese":         "San Marino",
	"São Toméan":           "Sao Tome and Principe",
	"Saudi":                "Saudi Arabia",
	"Senegalese":           "Senegal",
	"Serbian":              "Serbia",
	"Seychellois":          "Seychelles",
	"Sierra Leonean":       "Sierra Leone",
	"Singaporean":          "Singapore",
	"Slovak":               "Slovakia",
	"Slovene":              "Slovenia",
	"Solomon Islander":     "Solomon Islands",
	"Somali":               "Somalia",
	"South African":        "South Africa",
	"South Sudanese":       "South Sudan",
	"Spanish":              "Spain",
	"Sri Lankan":           "Sri Lanka",
	"Sudanese":             "Sudan",
	"Surinamese":           "Suriname",
	"Swedish":              "Sweden",
	"Swiss":                "Switzerland",
	"Syrian":               "Syria",
	"Taiwanese":            "Taiwan",
	"Tajik":                "Tajikistan",
	"Tanzanian":            "Tanzania",
	"Thai":                 "Thailand",
	"Timorese":             "Timor-Leste",
	"Togolese":             "Togo",
	"Tongan":               "Tonga",
	"Trinidadian":          "Trinidad and Tobago",
	"Tunisian":             "Tunisia",
	"Turkish":              "Turkey",
	"Turkmen":              "Turkmenistan",
	"Tuvaluan":             "Tuvalu",
	"Ugandan":              "Uganda",
	"Ukrainian":            "Ukraine",
	"Emirati":              "United Arab Emirates",
	"British":              "United Kingdom",
	"American":             "United States",
	"Uruguayan":            "Uruguay",
	"Uzbek":                "Uzbekistan",
	"Vanuatuan":            "Vanuatu",
	"Vatican":              "Vatican City",
	"Venezuelan":           "Venezuela",
	"Vietnamese":           "Vietnam",
	"Yemeni":               "Yemen",
	"Zambian":              "Zambia",
	"Zimbabwean":           "Zimbabwe",
}

var countryNames = []string{
	"Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
	"Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina",
	"Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Republic",
	"Chad", "Chile", "China", "Colombia", "Comoros", "Republic of the Congo", "Democratic Republic of the Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus",
	"Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia",
	"Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece",
	"Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia",
	"Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
	"North Korea", "South Korea", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
	"Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius",
	"Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
	"Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palau", "Panama",
	"Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis",
	"Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
	"Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden",
	"Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
	"Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
	"Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe",
}

var nationalities = []string{
	"Afghan", "Albanian", "Algerian", "Andorran", "Angolan", "Antiguan", "Argentine", "Armenian", "Australian", "Austrian", "Azerbaijani",
	"Bahamian", "Bahraini", "Bangladeshi", "Barbadian", "Belarusian", "Belgian", "Belizean", "Beninese", "Bhutanese", "Bolivian", "Bosnian",
	"Botswanan", "Brazilian", "Bruneian", "Bulgarian", "Burkinabé", "Burundian", "Cambodian", "Cameroonian", "Canadian", "Cape Verdean", "Central African",
	"Chadian", "Chilean", "Chinese", "Colombian", "Comorian", "Congolese", "Congolese (DRC)", "Costa Rican", "Croatian", "Cuban", "Cypriot",
	"Czech", "Danish", "Djiboutian", "Dominican", "Dominican (Republic)", "Ecuadorian", "Egyptian", "Salvadoran", "Equatorial Guinean", "Eritrean", "Estonian",
	"Swazi", "Ethiopian", "Fijian", "Finnish", "French", "Gabonese", "Gambian", "Georgian", "German", "Ghanaian", "Greek",
	"Grenadian", "Guatemalan", "Guinean", "Bissau-Guinean", "Guyanese", "Haitian", "Honduran", "Hungarian", "Icelandic", "Indian", "Indonesian",
	"Iranian", "Iraqi", "Irish", "Israeli", "Italian", "Jamaican", "Japanese", "Jordanian", "Kazakh", "Kenyan", "I-Kiribati",
	"North Korean", "South Korean", "Kuwaiti", "Kyrgyz", "Lao", "Latvian", "Lebanese", "Basotho", "Liberian", "Libyan", "Liechtensteiner",
	"Lithuanian", "Luxembourgish", "Malagasy", "Malawian", "Malaysian", "Maldivian", "Malian", "Maltese", "Marshallese", "Mauritanian", "Mauritian",
	"Mexican", "Micronesian", "Moldovan", "Monégasque", "Mongolian", "Montenegrin", "Moroccan", "Mozambican", "Burmese", "Namibian", "Nauruan",
	"Nepalese", "Dutch", "New Zealander", "Nicaraguan", "Nigerien", "Nigerian", "Norwegian", "Omani", "Pakistani", "Palauan", "Panamanian",
	"Papua New Guinean", "Paraguayan", "Peruvian", "Filipino", "Polish", "Portuguese", "Qatari", "Romanian", "Russian", "Rwandan", "Kittitian",
	"Saint Lucian", "Vincentian", "Samoan", "San Marinese", "São Toméan", "Saudi", "Senegalese", "Serbian", "Seychellois", "Sierra Leonean", "Singaporean",
	"Slovak", "Slovene", "Solomon Islander", "Somali", "South African", "South Sudanese", "Spanish", "Sri Lankan", "Sudanese", "Surinamese", "Swedish",
	"Swiss", "Syrian", "Taiwanese", "Tajik", "Tanzanian", "Thai", "Timorese", "Togolese", "Tongan", "Trinidadian", "Tunisian",
	"Turkish", "Turkmen", "Tuvaluan", "Ugandan", "Ukrainian", "Emirati", "British", "American", "Uruguayan", "Uzbek", "Vanuatuan",
	"Vatican", "Venezuelan", "Vietnamese", "Yemeni", "Zambian", "Zimbabwean",
}

var americanCities = []string{
	"New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia",
	"San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville",
	"San Francisco", "Columbus", "Fort Worth", "Indianapolis", "Charlotte", "Seattle",
	"Denver", "Washington D.C.", "Boston", "El Paso", "Nashville", "Detroit", "Oklahoma City",
	"Alabama",
	"Alaska",
	"Arizona",
	"Arkansas",
	"California",
	"Colorado",
	"Connecticut",
	"Delaware",
	"Florida",
	"Georgia",
	"Hawaii",
	"Idaho",
	"Illinois",
	"Indiana",
	"Iowa",
	"Kansas",
	"Kentucky",
	"Louisiana",
	"Maine",
	"Maryland",
	"Massachusetts",
	"Michigan",
	"Minnesota",
	"Mississippi",
	"Missouri",
	"Montana",
	"Nebraska",
	"Nevada",
	"New Hampshire",
	"New Jersey",
	"New Mexico",
	"New York",
	"North Carolina",
	"North Dakota",
	"Ohio",
	"Oklahoma",
	"Oregon",
	"Pennsylvania",
	"Rhode Island",
	"South Carolina",
	"South Dakota",
	"Tennessee",
	"Texas",
	"Utah",
	"Vermont",
	"Virginia",
	"Washington",
	"West Virginia",
	"Wisconsin",
	"Wyoming",
}

var MainDirectors = []string{
	"Director",
	"Game Director",
	"Creative Director",
	"Executive Director",
	"Lead Director",
	"Studio Director",
	"Franchise Director",
	"Project Director",
	"Production Director",
	"Series Director",
	"Supervising Director",
	"Managing Director",
	"Executive Producer", 
	"Co-Director",
	"Associate Director",
	"Chief Creative Officer",
	"Head of Studio",
	"Senior Director",
	"General Director",
	"Overall Director",
	"Supervising Creative Director",
	"Creative Lead",
	"Game Development Director",
	"Directed by",
}
